<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
/**
 * Packing comments list template
 *
 * @category    Mozg
 * @package     Mozg_BoxPacker
 * @author      Ultimate Module Creator
 */
?>
<?php $_packing = $this->getPacking()?>
<?php if ($_packing->getAllowComments()) : ?>
    <?php $_comments = $this->getComments(); ?>
    <?php if (count($_comments)) : ?>
        <div class="box-collateral box-reviews" id="packing-reviews">
            <h2><?php echo $this->__('Comments for: %s', $_packing->getReference()) ?></h2>
            <?php echo $this->getPagerHtml() ?>
            <dl>
                <?php foreach ($_comments as $_comment):?>
                <dt>
                    <div class="author"><?php echo $this->__('On %s %s wrote:', $this->formatDate($_comment->getCreatedAt(), 'long'), $this->escapeHtml($_comment->getName()))?></div>
                    <strong><?php echo $this->escapeHtml($_comment->getTitle()) ?></strong>
                </dt>
                <dd>
                    <?php echo nl2br($this->escapeHtml($_comment->getComment())) ?>
                </dd>
                <?php endforeach; ?>
            </dl>
            <?php echo $this->getPagerHtml() ?>
        </div>
    <?php endif;?>
    <?php echo $this->getChildHtml('comment_form') ?>
<?php endif;?>
